# Frontend proxy server routing traffic to various containers based on certain rules in nginx.conf
apiVersion: v1
kind: Service

metadata:
  name: frontend-proxy-server-service
  labels:
    app: frontend-proxy-server
    tier: frontend

spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: frontendproxy
  selector:
    app: frontend-proxy-server
    tier: frontend


---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend-proxy-server-deployment
  labels:
    app: frontend-proxy-server
    tier: frontend

spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-proxy-server
      tier: frontend

  template:
    metadata:
      labels:
        app: frontend-proxy-server
        tier: frontend

    spec:
      containers:
        - name: frontend-proxy-server
          image: nicklansley/gs1_digitallink_resolver_ce_frontend-proxy-server:v2.4.0
          ports:
            - containerPort: 80
              name: frontendproxy
