---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resolver-sql-pv-claim-data
  labels:
    app: resolver-sql-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resolver-sql-pv-claim-log
  labels:
    app: resolver-sql-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resolver-sql-pv-claim-secrets
  labels:
    app: resolver-sql-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  resolver-sql-pv-claim-backup
  labels:
    app: resolver-sql-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resolver-mongo-pv-claim
  labels:
    app: resolver-mongo-server
    tier: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi