# Data Entry API service with upload / download API
apiVersion: v1
kind: Service

metadata:
  name: data-entry-service

  labels:
    app: resolver-data-entry-server
    tier: frontend

spec:
  type: ClusterIP

  ports:
    - protocol: TCP
      port: 80
      targetPort: dataentryserver

  selector:
    app: resolver-data-entry-server
    tier: frontend

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: resolver-data-entry-server-deployment
  labels:
    app: resolver-data-entry-server
    tier: frontend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: resolver-data-entry-server
      tier: frontend

  template:
    metadata:
      labels:
        app: resolver-data-entry-server
        tier: frontend
    spec:
      containers:
        - name: resolver-data-entry-server

          image: nicklansley/gs1_digitallink_resolver_ce_resolver-data-entry-server:v2.3.0
          imagePullPolicy: IfNotPresent

          env:
            - name: PORT
              value: "80"
            - name: SQLDBCONN_USER
              valueFrom:
                secretKeyRef:
                  name: sqldbconn
                  key: user
            - name: SQLDBCONN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqldbconn
                  key: password
            - name: SQLDBCONN_SERVER
              valueFrom:
                secretKeyRef:
                  name: sqldbconn
                  key: server
            - name: SQLDBCONN_DB
              valueFrom:
                secretKeyRef:
                  name: sqldbconn
                  key: database

          ports:
            - containerPort: 80
              name: dataentryserver


